### PR TITLE
Added Oracle script, compatible with Oracle 11 and 12

### PR DESCRIPTION
**Pull request by jBarconsM**
Added Oracle script, compatible with Oracle 11 and 12

### CODE REVIEW

**Comment by fjlopez** [comment]
@jBarconsM, one quick doubt. This schema does not include a primary key value generation strategy (e.g. database sequences, database table to simulate sequence). In STM2, database sequences were used for Oracle, isn't?  Do you know what the primary key value generation strategies were for Postgres and SQL Server?

**Comment by fjlopez** [comment]
PR related to #2

**Review by fjlopez — APPROVED** [review]
PR related to #2

**Comment by jBarconsM** [comment]
STM2 en Oracle no tiene secuencias. Los ID se generan por código, con una llamada DWR que hace un SELECT Max(...)+1 en la tabla.

**Pull request merged**
